version: '3.8'

services:
  app:
    image: your-app-image:latest
    build: .
    container_name: your-app-container
    ports:
      - "8090:8090"
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
